"use strict";
!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="3120ef26-41a2-5c4c-8b0c-5b6aa217413d")}catch(e){}}();

Object.defineProperty(exports, "__esModule", { value: true });
exports.BankSeed = void 0;
exports.BankSeed = [
    { code: 'aceh', name: 'PT. BANK ACEH' },
    { code: 'aceh_syar', name: 'PT. BPD ISTIMEWA ACEH SYARIAH' },
    { code: 'agris', name: 'PT. BANK AGRIS' },
    { code: 'agroniaga', name: 'PT. BANK RAKYAT INDONESIA AGRONIAGA TBK.' },
    { code: 'allo', name: 'PT. ALLO BANK INDONESIA TBK.' },
    { code: 'amar', name: 'PT. BANK AMAR INDONESIA' },
    { code: 'andara', name: 'PT. BANK ANDARA' },
    { code: 'anglomas', name: 'PT. ANGLOMAS INTERNATIONAL BANK' },
    { code: 'antar_daerah', name: 'PT. BANK ANTAR DAERAH' },
    { code: 'anz', name: 'PT. BANK ANZ INDONESIA' },
    { code: 'artajasa', name: 'PT. ARTAJASA' },
    { code: 'artha', name: 'PT. BANK ARTHA GRAHA INTERNASIONAL TBK.' },
    { code: 'bali', name: 'PT. BANK PEMBANGUNAN DAERAH BALI' },
    { code: 'bangkok', name: 'BANGKOK BANK PUBLIC CO.LTD' },
    { code: 'banten', name: 'PT. BANK BANTEN' },
    { code: 'barclays', name: 'PT BANK BARCLAYS INDONESIA' },
    { code: 'bca', name: 'PT. BANK CENTRAL ASIA TBK.' },
    { code: 'bcad', name: 'PT. BANK DIGITAL BCA' },
    { code: 'bca_syar', name: 'PT. BANK BCA SYARIAH' },
    { code: 'bengkulu', name: 'PT. BPD BENGKULU' },
    { code: 'bisnis', name: 'PT. BANK BISNIS INTERNASIONAL' },
    { code: 'bjb', name: 'PT. BANK PEMBANGUNAN DAERAH JABAR DAN BANTEN' },
    { code: 'bjb_syar', name: 'PT. BANK JABAR BANTEN SYARIAH' },
    { code: 'bni', name: 'PT. BANK NEGARA INDONESIA (PERSERO)' },
    { code: 'bnp', name: 'PT. BANK NUSANTARA PARAHYANGAN' },
    { code: 'bnp_paribas', name: 'PT. BANK BNP PARIBAS INDONESIA' },
    { code: 'boa', name: 'BANK OF AMERICA NA' },
    { code: 'bri', name: 'PT. BANK RAKYAT INDONESIA (PERSERO)' },
    { code: 'bsi', name: 'PT. BANK SYARIAH INDONESIA TBK.' },
    { code: 'btn', name: 'PT. BANK TABUNGAN NEGARA (PERSERO)' },
    {
        code: 'btn_syar',
        name: 'PT. BANK TABUNGAN NEGARA (PERSERO) UNIT USAHA SYARIAH',
    },
    { code: 'btpn', name: 'PT. BANK BTPN' },
    { code: 'btpn_syar', name: 'PT. BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH' },
    { code: 'bukopin', name: 'PT BANK KB BUKOPIN TBK.' },
    { code: 'bukopin_syar', name: 'PT. BANK SYARIAH BUKOPIN' },
    { code: 'bumiputera', name: 'PT. BANK BUMIPUTERA' },
    { code: 'bumi_artha', name: 'PT. BANK BUMI ARTA' },
    { code: 'capital', name: 'PT BANK CAPITAL INDONESIA' },
    { code: 'centratama', name: 'PT. CENTRATAMA NASIONAL BANK' },
    { code: 'chase', name: 'JP MORGAN CHASE BANK, N.A' },
    { code: 'china', name: 'BANK OF CHINA' },
    { code: 'china_cons', name: 'CHINA CONSTRUCTION' },
    { code: 'chinatrust', name: 'PT. BANK CTBC INDONESIA' },
    { code: 'cimb', name: 'PT. BANK CIMB NIAGA TBK.' },
    { code: 'cimb_syar', name: 'PT. BANK CIMB NIAGA TBK. - UNIT USAHA SYARIAH' },
    {
        code: 'cimb_rekening_ponsel',
        name: 'PT. BANK CIMB NIAGA TBK. - REKENING PONSEL',
    },
    { code: 'citibank', name: 'CITIBANK, NA' },
    { code: 'commonwealth', name: 'PT. BANK COMMONWEALTH' },
    { code: 'danamon', name: 'PT. BANK DANAMON INDONESIA TBK.' },
    {
        code: 'danamon_syar',
        name: 'PT. BANK DANAMON INDONESIA UNIT USAHA SYARIAH',
    },
    { code: 'dbs', name: 'PT. BANK DBS INDONESIA' },
    { code: 'deutsche', name: 'DEUTSCHE BANK AG.' },
    { code: 'dipo', name: 'PT. BANK DIPO INTERNATIONAL' },
    { code: 'diy', name: 'PT. BANK PEMBANGUNAN DAERAH DIY' },
    {
        code: 'diy_syar',
        name: 'PT.BANK PEMBANGUNAN DAERAH DIY UNIT USAHA SYARIAH',
    },
    { code: 'dki', name: 'PT. BANK DKI' },
    { code: 'dki_syar', name: 'PT. BANK DKI UNIT USAHA SYARIAH' },
    { code: 'ekonomi', name: 'PT. BANK EKONOMI RAHARJA' },
    { code: 'fama', name: 'PT. BANK FAMA INTERNATIONAL' },
    { code: 'ganesha', name: 'PT. BANK GANESHA' },
    { code: 'gopay', name: 'GO-PAY' },
    { code: 'hana', name: 'PT. BANK KEB HANA INDONESIA' },
    { code: 'hs_1906', name: 'PT. BANK HS 1906' },
    { code: 'hsbc', name: 'PT. BANK HSBC INDONESIA' },
    { code: 'icbc', name: 'PT. BANK ICBC INDONESIA' },
    { code: 'ina_perdana', name: 'PT. BANK INA PERDANA' },
    { code: 'index_selindo', name: 'BANK INDEX SELINDO' },
    { code: 'india', name: 'PT. BANK OF INDIA INDONESIA TBK.' },
    { code: 'jago', name: 'PT. BANK JAGO TBK.' },
    { code: 'jambi', name: 'PT.BANK PEMBANGUNAN DAERAH JAMBI' },
    { code: 'jasa_jakarta', name: 'PT. BANK JASA JAKARTA' },
    { code: 'jateng', name: 'PT. BANK PEMBANGUNAN DAERAH JAWA TENGAH' },
    { code: 'jateng_syar', name: 'PT. BANK PEMBANGUNAN DAERAH JAWA TENGAH' },
    { code: 'jatim', name: 'PT. BANK PEMBANGUNAN DAERAH JATIM' },
    {
        code: 'jatim_syar',
        name: 'PT.BANK PEMBANGUNAN DAERAH JATIM - UNIT USAHA SYARIAH',
    },
    { code: 'jtrust', name: 'PT. BANK JTRUST INDONESIA TBK.' },
    { code: 'kalbar', name: 'PT.BANK PEMBANGUNAN DAERAH KALBAR' },
    { code: 'kalbar_syar', name: 'PT.BANK PEMBANGUNAN DAERAH KALBAR UUS' },
    { code: 'kalsel', name: 'PT. BANK PEMBANGUNAN DAERAH KALSEL' },
    {
        code: 'kalsel_syar',
        name: 'PT. BANK PEMBANGUNAN DAERAH KALSEL - UNIT USAHA SYARIAH',
    },
    { code: 'kalteng', name: 'PT. BPD KALIMANTAN TENGAH' },
    { code: 'kaltim', name: 'PT.BANK PEMBANGUNAN DAERAH KALTIM' },
    {
        code: 'kaltim_syar',
        name: 'PT.BANK PEMBANGUNAN DAERAH KALTIM - UNIT USAHA SYARIAH',
    },
    { code: 'lampung', name: 'PT.BANK PEMBANGUNAN DAERAH LAMPUNG' },
    { code: 'maluku', name: 'PT.BANK PEMBANGUNAN DAERAH MALUKU' },
    { code: 'mandiri', name: 'PT. BANK MANDIRI (PERSERO) TBK.' },
    { code: 'mandiri_taspen', name: 'PT. BANK MANDIRI TASPEN POS' },
    { code: 'maspion', name: 'PT. BANK MASPION' },
    { code: 'mayapada', name: 'PT. BANK MAYAPADA TBK.' },
    { code: 'maybank', name: 'PT. BANK MAYBANK INDONESIA TBK.' },
    { code: 'maybank_syar', name: 'PT. BANK MAYBANK SYARIAH INDONESIA' },
    {
        code: 'maybank_uus',
        name: 'PT. BANK MAYBANK INDONESIA TBK. UNIT USAHA SYARIAH',
    },
    { code: 'mayora', name: 'PT. BANK MAYORA' },
    { code: 'mega_syar', name: 'PT. BANK MEGA SYARIAH' },
    { code: 'mega_tbk', name: 'PT. BANK MEGA TBK.' },
    { code: 'mestika', name: 'PT. BANK MESTIKA DHARMA' },
    { code: 'metro', name: 'PT. BANK METRO EXPRESS' },
    { code: 'mitraniaga', name: 'PT. BANK MITRANIAGA' },
    { code: 'mitsubishi', name: 'THE BANK OF TOKYO MITSUBISHI UFJ LTD.' },
    { code: 'mizuho', name: 'PT. BANK MIZUHO INDONESIA' },
    { code: 'mnc', name: 'PT. BANK MNC INTERNASIONAL TBK.' },
    { code: 'muamalat', name: 'PT. BANK MUAMALAT INDONESIA' },
    { code: 'multiarta', name: 'PT. BANK MULTI ARTA SENTOSA' },
    { code: 'mutiara', name: 'PT. BANK MUTIARA TBK.' },
    { code: 'niaga_syar', name: 'PT. BANK NIAGA TBK. SYARIAH' },
    { code: 'nagari', name: 'PT. BANK NAGARI' },
    { code: 'nobu', name: 'PT. BANK NATIONALNOBU' },
    { code: 'ntb', name: 'PT. BANK PEMBANGUNAN DAERAH NTB' },
    { code: 'ntt', name: 'PT.BANK PEMBANGUNAN DAERAH NTT' },
    { code: 'ocbc', name: 'PT. BANK OCBC NISP TBK.' },
    { code: 'ocbc_syar', name: 'PT. BANK OCBC NISP TBK. - UNIT USAHA SYARIAH' },
    { code: 'ok', name: 'PT. BANK OKE INDONESIA' },
    { code: 'ovo', name: 'OVO' },
    { code: 'panin', name: 'PT. PANIN BANK TBK.' },
    { code: 'panin_syar', name: 'PT. BANK PANIN SYARIAH' },
    { code: 'papua', name: 'PT.BANK PEMBANGUNAN DAERAH PAPUA' },
    { code: 'permata', name: 'PT. BANK PERMATA TBK.' },
    { code: 'permata_syar', name: 'PT. BANK PERMATA TBK. UNIT USAHA SYARIAH' },
    { code: 'prima_master', name: 'PT. PRIMA MASTER BANK' },
    { code: 'pundi', name: 'PT. BANK PUNDI INDONESIA' },
    { code: 'purba', name: 'PT. BANK PURBA DANARTA' },
    { code: 'qnb', name: 'PT. BANK QNB INDONESIA TBK.' },
    { code: 'rabobank', name: 'PT. BANK RABOBANK INTERNATIONAL INDONESIA' },
    { code: 'rbos', name: 'THE ROYAL BANK OF SCOTLAND N.V.' },
    { code: 'resona', name: 'PT. BANK RESONA PERDANIA' },
    { code: 'riau', name: 'PT. BANK PEMBANGUNAN DAERAH RIAU KEPRI' },
    { code: 'riau_syar', name: 'PT. BANK PEMBANGUNAN DAERAH RIAU KEPRI SYARIAH' },
    { code: 'sampoerna', name: 'PT. BANK SAHABAT SAMPOERNA' },
    { code: 'sbi', name: 'PT. BANK SBI INDONESIA' },
    { code: 'seabank', name: 'PT. BANK SEABANK INDONESIA' },
    { code: 'shinhan', name: 'PT. BANK SHINHAN INDONESIA' },
    { code: 'sinarmas', name: 'PT. BANK SINARMAS' },
    { code: 'sinarmas_syar', name: 'PT. BANK SINARMAS UNIT USAHA SYARIAH' },
    { code: 'stanchard', name: 'STANDARD CHARTERED BANK' },
    { code: 'sulselbar', name: 'PT. BANK SULSELBAR' },
    { code: 'sulselbar_syar', name: 'PT. BANK SULSELBAR UNIT USAHA SYARIAH' },
    { code: 'sulteng', name: 'PT. BPD SULAWESI TENGAH' },
    { code: 'sultenggara', name: 'PT. BPD SULAWESI TENGGARA' },
    { code: 'sulut', name: 'PT. BANK SULUTGO' },
    { code: 'sumbar', name: 'BPD SUMATERA BARAT' },
    { code: 'sumitomo', name: 'PT. BANK SUMITOMO MITSUI INDONESIA' },
    { code: 'sumsel_babel', name: 'PT. BPD SUMSEL DAN BABEL' },
    {
        code: 'sumsel_babel_syar',
        name: 'PT. BPD SUMSEL DAN BABEL UNIT USAHA SYARIAH',
    },
    { code: 'sumut', name: 'PT. BANK PEMBANGUNAN DAERAH SUMUT' },
    { code: 'sumut_syar', name: 'PT. BANK PEMBANGUNAN DAERAH SUMUT UUS' },
    { code: 'uob', name: 'PT. BANK UOB INDONESIA' },
    { code: 'victoria', name: 'PT. BANK VICTORIA INTERNATIONAL' },
    { code: 'victoria_syar', name: 'PT. BANK VICTORIA SYARIAH' },
    { code: 'woori', name: 'PT. BANK WOORI SAUDARA INDONESIA 1906 TBK.' },
    { code: 'yudha_bhakti', name: 'PT. BANK YUDHA BHAKTI' },
];
//# sourceMappingURL=bank.seed.js.map
//# debugId=3120ef26-41a2-5c4c-8b0c-5b6aa217413d
