"use strict";
!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="00f95340-fbf0-5692-b2c9-73fac904a57d")}catch(e){}}();

Object.defineProperty(exports, "__esModule", { value: true });
exports.ClinicSeed = void 0;
const string_1 = require("../../src/globals/constant/string");
exports.ClinicSeed = [
    {
        name: 'Healthy Clinic',
        address: 'Jl. Sudirman No. 123',
        pinpoint_latitude: -6.1754,
        pinpoint_longitude: 106.8272,
        pinpoint_address: 'Jl. Sudirman No. 123, Jakarta',
        province_id: 1,
        city_id: 1,
        postal_code: 12345,
        registration_number: 987654,
        phone: '+621234567890',
        email: 'info@healthy-clinic.com',
        description: 'We are a modern clinic providing various healthcare services.',
        company_name: 'Healthy Clinic, Inc.',
        company_address: 'Jl. Thamrin No. 456',
        company_city_id: 1,
        company_province_id: 1,
        company_postal_code: 54321,
        npwp: '01.234.567.8-901.234',
        pic_name: 'John Doe',
        pic_phone: '+629876543210',
        contract_expired_date: new Date('2023-12-31'),
        clinic_operation_hours: {
            create: string_1.DayOfWeek.map((day) => {
                return {
                    day: day.name,
                    day_number: day.value,
                    start_time: new Date('2023-07-10 09:00'),
                    end_time: new Date('2023-07-10 17:00'),
                    is_active: true,
                };
            }),
        },
        treatments: {
            create: [
                {
                    name: 'Facial Treatment',
                    category: 'Facial Treatment',
                    description: 'A rejuvenating facial treatment that cleanses, exfoliates, and nourishes the skin, promoting a clear, well-hydrated complexion and can help your skin look younger.',
                    duration: '60 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Facial',
                    treatment_step: '1. Cleanse, 2. Exfoliate, 3. Steam, 4. Extractions, 5. Mask, 6. Massage, 7. Moisturize',
                    price: 500000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Manicure',
                    category: 'Nail Care',
                    description: 'A cosmetic beauty treatment for the fingernails and hands, including filing, shaping, and polishing.',
                    duration: '45 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Perawatan Tubuh',
                    treatment_step: '1. Remove old polish, 2. File and shape nails, 3. Cuticle care, 4. Hand massage, 5. Apply polish',
                    price: 150000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Liposuction',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to remove excess fat deposits from specific areas of the body.',
                    duration: '1-4 hours',
                    downtime: '14',
                    treatment_type: 'Bedah Plong',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Fat suction, 5. Closure',
                    price: 8000000,
                    method: 'Surgical',
                },
                {
                    name: 'Breast Augmentation',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to increase the size and improve the shape of the breasts.',
                    duration: '1-2 hours',
                    downtime: '14',
                    treatment_type: 'Bedah Estetik',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Breast implant insertion, 5. Closure',
                    price: 12000000,
                    method: 'Surgical',
                },
            ],
        },
    },
    {
        name: 'MediCare Clinic',
        address: 'Jl. Gatot Subroto No. 456',
        pinpoint_latitude: -6.2146,
        pinpoint_longitude: 106.8451,
        pinpoint_address: 'Jl. Gatot Subroto No. 456, Jakarta',
        province_id: 1,
        city_id: 2,
        postal_code: 54321,
        registration_number: 876543,
        phone: '+629876543210',
        email: 'info@medicare-clinic.com',
        description: 'We specialize in providing top-quality medical care to our patients.',
        company_name: 'MediCare Clinic, PT',
        company_address: 'Jl. M.H. Thamrin No. 789',
        company_city_id: 2,
        company_province_id: 1,
        company_postal_code: 98765,
        npwp: '01.234.567.8-901.234',
        pic_name: 'Jane Smith',
        pic_phone: '+628765432109',
        contract_expired_date: new Date('2023-11-30'),
        clinic_operation_hours: {
            create: string_1.DayOfWeek.map((day) => {
                return {
                    day: day.name,
                    day_number: day.value,
                    start_time: new Date('2023-07-10 09:00'),
                    end_time: new Date('2023-07-10 17:00'),
                    is_active: true,
                };
            }),
        },
        treatments: {
            create: [
                {
                    name: 'Haircut',
                    category: 'Hair Treatment',
                    description: 'A hair cutting service that includes consultation, shampoo, cut, and styling.',
                    duration: '30 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Hair Treatment',
                    treatment_step: '1. Consultation, 2. Shampoo, 3. Cut, 4. Styling',
                    price: 100000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Pedicure',
                    category: 'Nail Care',
                    description: 'A cosmetic beauty treatment for the toenails and feet, including filing, shaping, and polishing.',
                    duration: '45 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Perawatan Tubuh',
                    treatment_step: '1. Remove old polish, 2. File and shape nails, 3. Cuticle care, 4. Foot massage, 5. Apply polish',
                    price: 150000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Blepharoplasty',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to improve the appearance of the eyelids by removing excess skin, fat, or muscle.',
                    duration: '1-2 hours',
                    downtime: '14',
                    treatment_type: 'Bedah Estetik',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Tissue removal or repositioning, 5. Closure',
                    price: 10000000,
                    method: 'Surgical',
                },
                {
                    name: 'Rhytidectomy (Facelift)',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to reduce the appearance of facial wrinkles and other signs of aging.',
                    duration: '2-5 hours',
                    downtime: '28',
                    treatment_type: 'Facelift',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Tissue repositioning, 5. Closure',
                    price: 15000000,
                    method: 'Surgical',
                },
            ],
        },
    },
    {
        name: 'Graceful Health Clinic',
        address: 'Jl. Diponegoro No. 789',
        pinpoint_latitude: -7.2575,
        pinpoint_longitude: 112.7521,
        pinpoint_address: 'Jl. Diponegoro No. 789, Surabaya',
        province_id: 2,
        city_id: 3,
        postal_code: 67890,
        registration_number: 543210,
        phone: '+628765432109',
        email: 'info@gracefulhealth.com',
        description: 'A caring clinic dedicated to improving the health of our patients.',
        company_name: 'Graceful Health Clinic, PT',
        company_address: 'Jl. Soekarno-Hatta No. 123',
        company_city_id: 3,
        company_province_id: 2,
        company_postal_code: 45678,
        npwp: '02.345.678.9-012.345',
        pic_name: 'Michael Johnson',
        pic_phone: '+627654321098',
        contract_expired_date: new Date('2023-10-31'),
        clinic_operation_hours: {
            create: string_1.DayOfWeek.map((day) => {
                return {
                    day: day.name,
                    day_number: day.value,
                    start_time: new Date('2023-07-10 09:00'),
                    end_time: new Date('2023-07-10 17:00'),
                    is_active: true,
                };
            }),
        },
        treatments: {
            create: [
                {
                    name: 'Body Massage',
                    category: 'Massage Therapy',
                    description: 'A relaxing full-body massage that helps relieve stress and muscle tension.',
                    duration: '60 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Perawatan Tubuh',
                    treatment_step: '1. Consultation, 2. Prepare massage bed, 3. Apply oil, 4. Massage body, 5. Wipe off excess oil',
                    price: 250000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Hair Coloring',
                    category: 'Hair Care',
                    description: 'A hair coloring service that includes consultation, color application, and hair treatment.',
                    duration: '120 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Hair Treatment',
                    treatment_step: '1. Consultation, 2. Color application, 3. Hair treatment, 4. Rinse and dry',
                    price: 350000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Abdominoplasty (Tummy Tuck)',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to remove excess skin and fat from the abdomen and tighten the abdominal muscles.',
                    duration: '2-4 hours',
                    downtime: '14',
                    treatment_type: 'Tummy Tuck',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Tissue removal and muscle repair, 5. Closure',
                    price: 18000000,
                    method: 'Surgical',
                },
                {
                    name: 'Hair Transplantation',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to transplant hair follicles from one part of the body (donor site) to bald or balding areas (recipient site).',
                    duration: '4-8 hours',
                    downtime: '14',
                    treatment_type: 'Hair Treatment',
                    treatment_step: '1. Preoperative consultation, 2. Donor hair extraction, 3. Recipient site preparation, 4. Hair follicle transplantation, 5. Postoperative care',
                    price: 20000000,
                    method: 'Surgical',
                },
            ],
        },
    },
    {
        name: 'Eternal Health Clinic',
        address: 'Jl. Kebon Sirih No. 789',
        pinpoint_latitude: -6.1872,
        pinpoint_longitude: 106.8289,
        pinpoint_address: 'Jl. Kebon Sirih No. 789, Jakarta',
        province_id: 1,
        city_id: 1,
        postal_code: 54321,
        registration_number: 765432,
        phone: '+628765432109',
        email: 'info@eternalhealthclinic.com',
        description: 'Committed to providing comprehensive healthcare services.',
        company_name: 'Eternal Health Clinic, PT',
        company_address: 'Jl. Jendral Sudirman No. 567',
        company_city_id: 1,
        company_province_id: 1,
        company_postal_code: 98765,
        npwp: '01.345.678.9-012.345',
        pic_name: 'Emily Tan',
        pic_phone: '+627654321098',
        contract_expired_date: new Date('2023-09-30'),
        clinic_operation_hours: {
            create: string_1.DayOfWeek.map((day) => {
                return {
                    day: day.name,
                    day_number: day.value,
                    start_time: new Date('2023-07-10 09:00'),
                    end_time: new Date('2023-07-10 17:00'),
                    is_active: true,
                };
            }),
        },
        treatments: {
            create: [
                {
                    name: 'Facial Treatment',
                    category: 'Facial Treatment',
                    description: 'A rejuvenating facial treatment that cleanses, exfoliates, and nourishes the skin.',
                    duration: '90 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Facial',
                    treatment_step: '1. Cleanse, 2. Exfoliate, 3. Steam, 4. Extract, 5. Mask, 6. Massage, 7. Moisturize',
                    price: 300000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Waxing Service',
                    category: 'Hair Care',
                    description: 'A hair removal service that uses wax to remove unwanted hair.',
                    duration: '60 minutes',
                    downtime: '1',
                    treatment_type: 'Perawatan Tubuh',
                    treatment_step: '1. Cleanse skin, 2. Apply wax, 3. Remove hair, 4. Apply soothing lotion',
                    price: 180000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Rhinoplasty (Nose Job)',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to reshape or resize the nose for aesthetic purposes.',
                    duration: '1-2 hours',
                    downtime: '14',
                    treatment_type: 'Bedah Estetik',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Nose reshaping, 5. Closure',
                    price: 12000000,
                    method: 'Surgical',
                },
                {
                    name: 'Breast Reduction Surgery',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to reduce the size and reshape the breasts for cosmetic and functional purposes.',
                    duration: '2-4 hours',
                    downtime: '28',
                    treatment_type: 'Bedah Estetik',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Breast tissue removal, 5. Reshaping, 6. Closure',
                    price: 15000000,
                    method: 'Surgical',
                },
            ],
        },
    },
    {
        name: 'Harmony Medical Center',
        address: 'Jl. Asia Afrika No. 456',
        pinpoint_latitude: -6.9214,
        pinpoint_longitude: 107.6049,
        pinpoint_address: 'Jl. Asia Afrika No. 456, Bandung',
        province_id: 2,
        city_id: 4,
        postal_code: 78901,
        registration_number: 987654,
        phone: '+629876543210',
        email: 'info@harmonymedicalcenter.com',
        description: 'Dedicated to providing compassionate medical care to our patients.',
        company_name: 'Harmony Medical Center, PT',
        company_address: 'Jl. Merdeka No. 123',
        company_city_id: 4,
        company_province_id: 2,
        company_postal_code: 54321,
        npwp: '02.456.789.0-123.456',
        pic_name: 'David Lee',
        pic_phone: '+628765432109',
        contract_expired_date: new Date('2023-08-31'),
        clinic_operation_hours: {
            create: string_1.DayOfWeek.map((day) => {
                return {
                    day: day.name,
                    day_number: day.value,
                    start_time: new Date('2023-07-10 09:00'),
                    end_time: new Date('2023-07-10 17:00'),
                    is_active: true,
                };
            }),
        },
        treatments: {
            create: [
                {
                    name: 'Manicure',
                    category: 'Nail Care',
                    description: 'A beauty treatment for the hands and nails, including nail shaping and polish.',
                    duration: '45 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Perawatan Tubuh',
                    treatment_step: '1. Remove old polish, 2. File and shape nails, 3. Cuticle care, 4. Hand massage, 5. Apply polish',
                    price: 120000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Facial Treatment',
                    category: 'Facial Treatment',
                    description: 'A rejuvenating facial treatment that cleanses, exfoliates, and nourishes the skin.',
                    duration: '90 minutes',
                    downtime: 'No downtime',
                    treatment_type: 'Facial',
                    treatment_step: '1. Cleanse, 2. Exfoliate, 3. Steam, 4. Extract, 5. Mask, 6. Massage, 7. Moisturize',
                    price: 300000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Waxing Service',
                    category: 'Hair Care',
                    description: 'A hair removal service that uses wax to remove unwanted hair.',
                    duration: '60 minutes',
                    downtime: '1',
                    treatment_type: 'Hair Treatment',
                    treatment_step: '1. Cleanse skin, 2. Apply wax, 3. Remove hair, 4. Apply soothing lotion',
                    price: 180000,
                    method: 'Non-Surgical',
                },
                {
                    name: 'Lip Augmentation',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to enhance the size and shape of the lips for a fuller and more youthful appearance.',
                    duration: '1-2 hours',
                    downtime: 'No downtime',
                    treatment_type: 'Filler',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Lip filler insertion, 5. Closure',
                    price: 8000000,
                    method: 'Surgical',
                },
                {
                    name: 'Eyelid Surgery (Blepharoplasty)',
                    category: 'Plastic Surgery',
                    description: 'A surgical procedure to improve the appearance of the eyelids by removing excess skin, fat, or muscle.',
                    duration: '1-2 hours',
                    downtime: '14',
                    treatment_type: 'Bedah Estetik',
                    treatment_step: '1. Preoperative consultation, 2. Anesthesia administration, 3. Incision, 4. Tissue removal or repositioning, 5. Closure',
                    price: 10000000,
                    method: 'Surgical',
                },
            ],
        },
    },
];
//# sourceMappingURL=clinic.seed.js.map
//# debugId=00f95340-fbf0-5692-b2c9-73fac904a57d
