"use strict";
!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="8a9b9c78-8878-589c-b6f8-0d2981f42f02")}catch(e){}}();

Object.defineProperty(exports, "__esModule", { value: true });
exports.DoctorSchedulesSeed = void 0;
exports.DoctorSchedulesSeed = [
    {
        start_end_time: '[09:00-11:00,13:00-15:00]',
        day: 'Monday',
        day_number: 1,
        userId: 4,
        status: true,
    },
    {
        start_end_time: '[14:00-16:00]',
        day: 'Tuesday',
        day_number: 2,
        userId: 4,
        status: true,
    },
    {
        start_end_time: '[10:00-12:00,16:00-18:00]',
        day: 'Wednesday',
        day_number: 3,
        userId: 4,
        status: true,
    },
    {
        start_end_time: '[13:00-15:00,17:00-19:00]',
        day: 'Thursday',
        day_number: 4,
        userId: 4,
        status: true,
    },
    {
        start_end_time: '[08:00-10:00,12:00-14:00]',
        day: 'Friday',
        day_number: 5,
        userId: 4,
        status: true,
    },
    {
        start_end_time: '[11:00-13:00]',
        day: 'Saturday',
        day_number: 6,
        userId: 4,
        status: true,
    },
    {
        start_end_time: '[16:00-18:00]',
        day: 'Sunday',
        day_number: 0,
        userId: 4,
        status: true,
    },
    {
        start_end_time: '[08:30-10:30,14:30-16:30]',
        day: 'Monday',
        day_number: 1,
        userId: 5,
        status: true,
    },
    {
        start_end_time: '[12:30-14:30,16:30-18:30]',
        day: 'Tuesday',
        day_number: 2,
        userId: 5,
        status: true,
    },
    {
        start_end_time: '[09:30-11:30,13:30-15:30]',
        day: 'Wednesday',
        day_number: 3,
        userId: 5,
        status: true,
    },
    {
        start_end_time: '[11:30-13:30,15:30-17:30]',
        day: 'Thursday',
        day_number: 4,
        userId: 5,
        status: true,
    },
    {
        start_end_time: '[10:30-12:30,14:30-16:30]',
        day: 'Friday',
        day_number: 5,
        userId: 5,
        status: true,
    },
    {
        start_end_time: '[13:30-15:30]',
        day: 'Saturday',
        day_number: 6,
        userId: 5,
        status: true,
    },
    {
        start_end_time: '[09:30-11:30]',
        day: 'Monday',
        day_number: 1,
        userId: 6,
        status: true,
    },
    {
        start_end_time: '[13:30-15:30,17:30-19:30]',
        day: 'Tuesday',
        day_number: 2,
        userId: 6,
        status: true,
    },
    {
        start_end_time: '[10:30-12:30,14:30-16:30]',
        day: 'Wednesday',
        day_number: 3,
        userId: 6,
        status: true,
    },
    {
        start_end_time: '[11:30-13:30,15:30-17:30]',
        day: 'Thursday',
        day_number: 4,
        userId: 6,
        status: true,
    },
    {
        start_end_time: '[14:00-16:00]',
        day: 'Friday',
        day_number: 5,
        userId: 6,
        status: true,
    },
    {
        start_end_time: '[16:00-18:00]',
        day: 'Sunday',
        day_number: 0,
        userId: 6,
        status: true,
    },
    {
        start_end_time: '[14:00-16:00]',
        day: 'Monday',
        day_number: 1,
        userId: 7,
        status: true,
    },
    {
        start_end_time: '[13:00-15:00,17:00-19:00]',
        day: 'Tuesday',
        day_number: 2,
        userId: 7,
        status: true,
    },
    {
        start_end_time: '[09:00-11:00,15:00-17:00]',
        day: 'Wednesday',
        day_number: 3,
        userId: 7,
        status: true,
    },
    {
        start_end_time: '[11:00-13:00,17:00-19:00]',
        day: 'Thursday',
        day_number: 4,
        userId: 7,
        status: true,
    },
    {
        start_end_time: '[08:00-10:00]',
        day: 'Friday',
        day_number: 5,
        userId: 7,
        status: true,
    },
    {
        start_end_time: '[13:00-15:00,16:00-18:00]',
        day: 'Saturday',
        day_number: 6,
        userId: 7,
        status: true,
    },
    {
        start_end_time: '[15:00-17:00]',
        day: 'Sunday',
        day_number: 0,
        userId: 7,
        status: true,
    },
];
//# sourceMappingURL=doctor-schedules.seed.js.map
//# debugId=8a9b9c78-8878-589c-b6f8-0d2981f42f02
