"use strict";
!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="9a744c55-5f81-575c-90ab-401163391a02")}catch(e){}}();

Object.defineProperty(exports, "__esModule", { value: true });
exports.ProductSeed = void 0;
const client_1 = require("@prisma/client");
exports.ProductSeed = [
    {
        name: 'ISISPHARMA',
        type: client_1.product_type.SKINCARE,
        category: 'Cleanser',
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 200000,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        skincare_detail: {
            create: {
                brand: 'ISISPHARMA',
                description: 'Cleanser untuk Jerawat',
                specification_texture: 'Gel',
                specification_bpom: '12345678',
                specification_netto: 100,
                specification_netto_type: 'ml',
                specification_expired: new Date('2024-12-31'),
                specification_packaging_type: 'Tube',
                specification_ingredients: 'Aqua, Glycerin, Salicylic Acid, etc.',
                specification_how_to_use: 'Gunakan pada wajah yang basah, pijat lembut, lalu bilas.',
                specification_storage_advice: 'Simpan di tempat sejuk dan kering.',
            },
        },
    },
    {
        name: 'Niacinamide 10% + Zinc 1%',
        type: client_1.product_type.SKINCARE,
        category: 'Serum',
        display: 'Semua jenis kulit',
        has_variant: false,
        min_order: 1,
        price: 150000,
        product_is_active: true,
        product_stock: 20,
        product_threshold: '5',
        product_sku: 'SKU-NIA-001',
        shipping_product_weight: 50,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 10,
        shipping_product_size_width: 5,
        shipping_product_size_height: 3,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: 'The Ordinary',
                description: 'Serum wajah dengan konsentrat Niacinamide dan Zinc untuk kulit berminyak dan berjerawat.',
                specification_texture: 'Cair',
                specification_bpom: 'N/A',
                specification_netto: 30,
                specification_netto_type: 'ml',
                specification_expired: new Date('2023-08-31'),
                specification_packaging_type: 'Botol kaca dengan pipet',
                specification_ingredients: 'Aqua, Niacinamide, Zinc PCA, etc.',
                specification_how_to_use: 'Oleskan beberapa tetes pada wajah yang bersih sebelum menggunakan pelembap.',
                specification_storage_advice: 'Simpan di tempat yang sejuk dan terhindar dari sinar matahari langsung.',
            },
        },
    },
    {
        name: 'CeraVe Hydrating Cleanser',
        type: client_1.product_type.SKINCARE,
        category: 'Cleanser',
        display: 'Semua jenis kulit',
        has_variant: false,
        min_order: 1,
        price: 120000,
        product_is_active: true,
        product_stock: 15,
        product_threshold: '5',
        product_sku: 'SKU-CRV-001',
        shipping_product_weight: 100,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 8,
        shipping_product_size_width: 5,
        shipping_product_size_height: 3,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: 'CeraVe',
                description: 'Pembersih wajah lembut dengan teknologi MVE yang membantu melembapkan kulit.',
                specification_texture: 'Gel',
                specification_bpom: 'N/A',
                specification_netto: 100,
                specification_netto_type: 'ml',
                specification_expired: new Date('2023-12-31'),
                specification_packaging_type: 'Tube',
                specification_ingredients: 'Aqua, Glycerin, Ceramide NP, etc.',
                specification_how_to_use: 'Basahi wajah, aplikasikan pembersih secara merata, pijat lembut, dan bilas dengan air.',
                specification_storage_advice: 'Simpan di tempat yang sejuk dan kering.',
            },
        },
    },
    {
        name: 'La Roche-Posay Effaclar Duo+',
        type: client_1.product_type.SKINCARE,
        category: 'Treatment',
        display: 'Acne',
        has_variant: false,
        min_order: 1,
        price: 250000,
        product_is_active: true,
        product_stock: 10,
        product_threshold: null,
        product_sku: 'LRP-ED-001',
        shipping_product_weight: 50,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 10,
        shipping_product_size_width: 5,
        shipping_product_size_height: 15,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: 'La Roche-Posay',
                description: 'Krim jerawat yang membantu mengurangi jerawat dan bekasnya. Mengandung salicylic acid dan niacinamide.',
                specification_texture: 'Gel-Cream',
                specification_bpom: 'NA18191301234',
                specification_netto: 40,
                specification_netto_type: 'ml',
                specification_expired: new Date('2023-12-31'),
                specification_packaging_type: 'Tube',
                specification_ingredients: 'Aqua, Glycerin, Salicylic Acid, Niacinamide, etc.',
                specification_how_to_use: 'Oleskan pada wajah yang bersih, gunakan pagi dan malam.',
                specification_storage_advice: 'Simpan di tempat yang sejuk dan terhindar dari sinar matahari langsung.',
            },
        },
    },
    {
        name: 'Drunk Elephant T.L.C. Sukari Babyfacial',
        type: client_1.product_type.SKINCARE,
        category: 'Mask',
        display: 'All Skin Types',
        has_variant: false,
        min_order: 1,
        price: 600000,
        product_is_active: true,
        product_stock: 10,
        product_threshold: null,
        product_sku: 'DE-SUKARI-123',
        shipping_product_weight: 100,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 10,
        shipping_product_size_width: 5,
        shipping_product_size_height: 5,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: 'Drunk Elephant',
                description: 'AHA/BHA facial treatment to exfoliate and resurface skin.',
                specification_texture: 'Cream',
                specification_bpom: '98765432',
                specification_netto: 50,
                specification_netto_type: 'ml',
                specification_expired: new Date('2023-08-31'),
                specification_packaging_type: 'Bottle',
                specification_ingredients: 'Glycerin, Glycolic Acid, Salicylic Acid, etc.',
                specification_how_to_use: 'Apply an even layer to clean, dry skin. Leave on for 20 minutes, then rinse off with warm water. Use once a week.',
                specification_storage_advice: 'Store in a cool, dry place and avoid direct sunlight.',
            },
        },
    },
    {
        name: 'Skinceuticals C E Ferulic',
        type: client_1.product_type.SKINCARE,
        category: 'Serum',
        display: 'All Skin Types',
        has_variant: false,
        min_order: 1,
        price: 350000,
        product_is_active: true,
        product_stock: 10,
        product_threshold: '3',
        product_sku: 'SC-FERULIC-123',
        shipping_product_weight: 50,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 5,
        shipping_product_size_height: 12,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: 'Skinceuticals',
                description: "Skinceuticals C E Ferulic is a high-potency vitamin C serum that delivers advanced environmental protection and improves the appearance of fine lines and wrinkles, loss of firmness, and brightens skin's complexion.",
                specification_texture: 'Serum',
                specification_bpom: 'NA',
                specification_netto: 30,
                specification_netto_type: 'ml',
                specification_expired: new Date('2024-06-30'),
                specification_packaging_type: 'Bottle',
                specification_ingredients: 'Aqua/Water, L-Ascorbic Acid (Vitamin C), Ethoxydiglycol, Propylene Glycol, Glycerin, Laureth-23, Phenoxyethanol, Tocopherol (Vitamin E), Ferulic Acid, Sodium Hyaluronate, Sodium Hydroxide.',
                specification_how_to_use: 'In the morning, after cleansing and toning, apply 4-5 drops of Skinceuticals C E Ferulic to a dry face, neck, and chest before other skincare products. Avoid the eye area. Follow with a moisturizer and sunscreen.',
                specification_storage_advice: 'Store in a cool, dark place. Avoid exposure to direct sunlight.',
            },
        },
    },
    {
        name: 'The Body Shop Tea Tree Oil',
        type: client_1.product_type.SKINCARE,
        category: 'Serum',
        display: 'Acne',
        has_variant: false,
        min_order: 1,
        price: 120000,
        product_is_active: true,
        product_stock: 10,
        product_threshold: '3',
        product_sku: 'TBS-TTO-001',
        shipping_product_weight: 50,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 10,
        shipping_product_size_width: 4,
        shipping_product_size_height: 4,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: 'The Body Shop',
                description: 'The Body Shop Tea Tree Oil adalah minyak tea tree murni yang membantu mengatasi jerawat dan kulit berminyak.',
                specification_texture: 'Oil',
                specification_bpom: 'NA18181201223',
                specification_netto: 10,
                specification_netto_type: 'ml',
                specification_expired: new Date('2023-12-31'),
                specification_packaging_type: 'Bottle',
                specification_ingredients: 'Melaleuca Alternifolia (Tea Tree) Leaf Oil',
                specification_how_to_use: 'Oleskan langsung pada area yang bermasalah dengan kapas.',
                specification_storage_advice: 'Simpan di tempat yang sejuk dan kering, hindari sinar matahari langsung.',
            },
        },
    },
    {
        name: "Paula's Choice 2% BHA Liquid Exfoliant",
        type: client_1.product_type.SKINCARE,
        category: 'Exfoliant',
        display: 'All Skin Types',
        has_variant: false,
        min_order: 1,
        price: 350000,
        product_is_active: true,
        product_stock: 20,
        product_threshold: '5',
        product_sku: 'PC-BHA-EXF-123',
        shipping_product_weight: 150,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 15,
        shipping_product_size_width: 5,
        shipping_product_size_height: 3,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: "Paula's Choice",
                description: "Paula's Choice 2% BHA Liquid Exfoliant is a leave-on exfoliator with salicylic acid to help unclog pores and improve skin texture.",
                specification_texture: 'Liquid',
                specification_bpom: 'NA',
                specification_netto: 100,
                specification_netto_type: 'ml',
                specification_expired: new Date('2024-06-30'),
                specification_packaging_type: 'Bottle',
                specification_ingredients: 'Water, Butylene Glycol, Salicylic Acid, etc.',
                specification_how_to_use: 'Apply once or twice daily after cleansing and toning. Dispense a few drops on a cotton pad and apply to face. Avoid eye area.',
                specification_storage_advice: 'Store in a cool, dry place and keep away from direct sunlight.',
            },
        },
    },
    {
        name: "Kiehl's Ultra Facial Cream",
        type: client_1.product_type.SKINCARE,
        category: 'Moisturizer',
        display: 'Normal',
        has_variant: false,
        min_order: 1,
        price: 350000,
        product_is_active: true,
        product_stock: 20,
        product_threshold: '5',
        product_sku: 'KIE-123-UFC',
        shipping_product_weight: 150,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 10,
        shipping_product_size_width: 10,
        shipping_product_size_height: 10,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: "Kiehl's",
                description: "Kiehl's Ultra Facial Cream adalah pelembap wajah yang ringan dan cocok untuk semua jenis kulit.",
                specification_texture: 'Cream',
                specification_bpom: '98765432',
                specification_netto: 50,
                specification_netto_type: 'ml',
                specification_expired: new Date('2024-12-31'),
                specification_packaging_type: 'Jar',
                specification_ingredients: 'Aqua, Squalane, Glycerin, etc.',
                specification_how_to_use: 'Oleskan pada wajah yang bersih, gunakan pagi dan malam.',
                specification_storage_advice: 'Simpan di tempat yang sejuk dan terhindar dari sinar matahari langsung.',
            },
        },
    },
    {
        name: 'Laneige Water Sleeping Mask',
        type: client_1.product_type.SKINCARE,
        category: 'Mask',
        display: 'All Skin Types',
        has_variant: false,
        min_order: 1,
        price: 350000,
        product_is_active: true,
        product_stock: 10,
        product_threshold: null,
        product_sku: 'LSM-123-WTR',
        shipping_product_weight: 150,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 10,
        shipping_product_size_width: 10,
        shipping_product_size_height: 5,
        shipping: 'Instant|Regular',
        skincare_detail: {
            create: {
                brand: 'Laneige',
                description: 'Laneige Water Sleeping Mask is an overnight face mask that hydrates and revitalizes your skin while you sleep.',
                specification_texture: 'Gel',
                specification_bpom: 'N/A',
                specification_netto: 70,
                specification_netto_type: 'ml',
                specification_expired: new Date('2023-09-30'),
                specification_packaging_type: 'Jar',
                specification_ingredients: 'Water, Butylene Glycol, Cyclopentasiloxane, etc.',
                specification_how_to_use: 'Apply a generous amount to your face and neck as the last step of your nighttime skincare routine. Leave it on overnight and rinse off in the morning.',
                specification_storage_advice: 'Store in a cool, dry place, away from direct sunlight.',
            },
        },
    },
    {
        name: 'Digenta Cream',
        type: client_1.product_type.DRUGS,
        category: null,
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 136000,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        drug_detail: {
            create: {
                manufacture: 'ISISPHARMA',
                indication: 'Mengatasi jerawat dan peradangan kulit',
                contradiction: 'Tidak boleh digunakan oleh orang dengan riwayat alergi terhadap kandungan Digenta Cream',
                description: 'Digenta Cream adalah obat luar yang digunakan untuk mengatasi jerawat dan peradangan pada kulit yang sensitif terhadap kortikosteroid, serta disertai oleh infeksi bakteri tertentu.',
                specification_form: 'Krim',
                specification_classification: 'Obat Keras (Merah)',
                specification_type: 'Topikal',
                specification_packaging: 'Tube',
                specification_category: 'Antiinflamasi',
                specification_bpom: 'XXXXXX',
                specification_ingredients: 'Mengandung zat aktif X dan zat bantu Y',
                specification_dose: 'Oleskan tipis ke area yang terkena dua kali sehari',
                specification_special_attention: 'Hanya untuk penggunaan luar, hindari kontak dengan mata dan luka terbuka.',
            },
        },
    },
    {
        name: 'Noroid Soothing Cream',
        type: client_1.product_type.DRUGS,
        category: null,
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 152500,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        drug_detail: {
            create: {
                manufacture: 'PT XYZ Pharmaceuticals',
                indication: 'Mengurangi peradangan dan iritasi pada kulit.',
                contradiction: 'Tidak boleh digunakan oleh orang yang memiliki alergi terhadap salah satu bahan dalam krim ini.',
                description: 'Noroid Soothing Cream adalah krim yang dirancang untuk meredakan peradangan pada kulit akibat jerawat.',
                specification_form: 'Krim',
                specification_classification: 'Obat Bebas (Hijau)',
                specification_type: 'Topikal',
                specification_packaging: 'Tube',
                specification_category: 'Antiinflamasi',
                specification_bpom: '123456789',
                specification_ingredients: 'Aqua, Glycerin, Zinc Oxide, Cetyl Alcohol, dll.',
                specification_dose: 'Oleskan tipis-tipis pada area kulit yang terkena dua kali sehari.',
                specification_special_attention: 'Hanya untuk penggunaan luar. Hindari kontak dengan mata dan luka terbuka.',
            },
        },
    },
    {
        name: 'Benzoyl Peroxide',
        type: client_1.product_type.DRUGS,
        category: null,
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 25000,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        drug_detail: {
            create: {
                manufacture: 'ISISPHARMA',
                indication: 'Digunakan untuk mengobati jerawat dan mencegahnya kembali.',
                contradiction: 'Tidak cocok untuk orang dengan riwayat alergi terhadap Benzoyl Peroxide.',
                description: 'Benzoyl Peroxide adalah bahan aktif yang efektif untuk mengatasi jerawat. Ini bekerja dengan membunuh bakteri penyebab jerawat dan membersihkan pori-pori kulit.',
                specification_form: 'Salep',
                specification_classification: 'Obat Bebas (Hijau)',
                specification_type: 'Topikal',
                specification_packaging: 'Tube',
                specification_category: 'Antibiotik',
                specification_bpom: '123456789',
                specification_ingredients: 'Benzoyl Peroxide 5%',
                specification_dose: 'Oleskan tipis pada area jerawat 1-2 kali sehari',
                specification_special_attention: 'Hindari kontak dengan mata dan mulut. Jangan digunakan pada kulit yang iritasi atau terluka.',
            },
        },
    },
    {
        name: 'Retinoid Cream',
        type: client_1.product_type.DRUGS,
        category: null,
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 720000,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        drug_detail: {
            create: {
                manufacture: 'ISISPHARMA',
                indication: 'Mengobati jerawat',
                contradiction: 'Tidak boleh digunakan oleh ibu hamil',
                description: 'Retinoid Cream adalah krim yang mengandung retinoid untuk mengatasi jerawat',
                specification_form: 'Krim',
                specification_classification: 'Obat Keras (Merah)',
                specification_type: 'Topikal',
                specification_packaging: 'Tube',
                specification_category: 'Antiinflamasi',
                specification_bpom: '12345678',
                specification_ingredients: 'Retinoid, water, glycerin',
                specification_dose: 'Oleskan tipis-tipis pada area jerawat',
                specification_special_attention: 'Hanya untuk digunakan pada malam hari',
            },
        },
    },
    {
        name: 'Eucerin Advanced Repair Cream',
        type: client_1.product_type.DRUGS,
        category: null,
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 240000,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        drug_detail: {
            create: {
                manufacture: 'Eucerin',
                indication: 'Menghidrasi kulit kering dan kasar',
                contradiction: 'Tidak boleh digunakan jika terjadi reaksi alergi terhadap salah satu komponen produk',
                description: 'Eucerin Advanced Repair Cream adalah krim yang diformulasikan khusus untuk membantu menghidrasi dan merawat kulit yang kering, kasar, atau teriritasi.',
                specification_form: 'Krim',
                specification_classification: 'Obat Bebas (Hijau)',
                specification_type: 'Topikal',
                specification_packaging: 'Tube',
                specification_category: 'Antiinflamasi',
                specification_bpom: '123456789',
                specification_ingredients: 'Aqua, Glycerin, Urea, Cetearyl Alcohol, Sodium Lactate, Caprylic/Capric Triglyceride, Ethylhexyl Cocoate, Hydrogenated Coco-Glycerides, Octyldodecanol, Sorbitan Stearate, Polysorbate 60, Dimethicone, Glyceryl Stearate SE, Aluminum Starch Octenylsuccinate, Sodium Cetearyl Sulfate, Xanthan Gum, Lactic Acid, Pentylene Glycol, Butylene Glycol, Benzyl Alcohol, Phenoxyethanol',
                specification_dose: 'Oleskan pada area kulit yang kering dan kasar secara merata',
                specification_special_attention: 'Hentikan penggunaan jika terjadi iritasi atau reaksi alergi.',
            },
        },
    },
    {
        name: 'Cetaphil Gentle Skin Cleanser',
        type: client_1.product_type.DRUGS,
        category: null,
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 112000,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        drug_detail: {
            create: {
                manufacture: 'Galderma',
                indication: 'Membersihkan dan merawat kulit sensitif',
                contradiction: 'Hanya untuk penggunaan luar, hindari kontak dengan mata',
                description: 'Cetaphil Gentle Skin Cleanser adalah pembersih wajah yang lembut dan efektif untuk membersihkan kulit sensitif tanpa mengiritasi.',
                specification_form: 'Krim',
                specification_classification: 'Obat Bebas (Hijau)',
                specification_type: 'Topikal',
                specification_packaging: 'Botol',
                specification_category: 'Analgesik',
                specification_bpom: '12345678',
                specification_ingredients: 'Aqua, Cetyl Alcohol, Propylene Glycol, Sodium Lauryl Sulfate, Stearyl Alcohol, Methylparaben, Propylparaben, Butylparaben',
                specification_dose: 'Gunakan secukupnya, aplikasikan pada wajah, pijat lembut, lalu bilas dengan air',
                specification_special_attention: 'Hentikan penggunaan jika terjadi iritasi',
            },
        },
    },
    {
        name: 'Clotrimazole Cream',
        type: client_1.product_type.DRUGS,
        category: null,
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 40000,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        drug_detail: {
            create: {
                manufacture: 'PT Pharma XYZ',
                indication: 'Untuk mengobati infeksi jamur pada kulit.',
                contradiction: 'Tidak boleh digunakan oleh pasien yang memiliki alergi terhadap clotrimazole.',
                description: 'Clotrimazole Cream adalah obat topikal yang digunakan untuk mengobati infeksi jamur pada kulit seperti kurap, panu, dan gatal-gatal lainnya.',
                specification_form: 'Salep',
                specification_classification: 'Obat bebas (Hijau)',
                specification_type: 'Topikal',
                specification_packaging: 'Tube',
                specification_category: 'Antibiotik',
                specification_bpom: '123456789',
                specification_ingredients: 'Clotrimazole 1%',
                specification_dose: 'Oleskan tipis pada area yang terinfeksi 2-3 kali sehari.',
                specification_special_attention: 'Hentikan penggunaan jika timbul reaksi alergi.',
            },
        },
    },
    {
        name: 'Hydrocortisone Cream',
        type: client_1.product_type.DRUGS,
        category: null,
        display: 'Jerawat',
        has_variant: false,
        min_order: 1,
        price: 8000,
        product_is_active: true,
        product_stock: 8,
        product_threshold: null,
        product_sku: null,
        shipping_product_weight: 10,
        shipping_product_weight_type: 'gr',
        shipping_product_size_length_type: 'cm',
        shipping_product_size_width_type: 'cm',
        shipping_product_size_height_type: 'cm',
        shipping_product_size_length: 5,
        shipping_product_size_width: 10,
        shipping_product_size_height: 20,
        shipping: 'Instant|Same Day|Regular',
        drug_detail: {
            create: {
                manufacture: 'PT Pharma Company',
                indication: 'For the relief of itching and inflammation associated with skin conditions such as eczema, dermatitis, and insect bites.',
                contradiction: 'Do not use on broken skin, face, or genitals. Avoid contact with eyes.',
                description: 'Hydrocortisone Cream is a topical corticosteroid that helps to reduce redness, swelling, and itching.',
                specification_form: 'Krim',
                specification_classification: 'Obat Bebas (Hijau)',
                specification_type: 'Topical',
                specification_packaging: 'Tube',
                specification_category: 'Antiinflamasi',
                specification_bpom: 'Registered with BPOM Indonesia',
                specification_ingredients: 'Hydrocortisone 1%',
                specification_dose: 'Apply a thin layer to the affected area 2-3 times daily',
                specification_special_attention: 'Avoid prolonged use without medical supervision.',
            },
        },
    },
];
//# sourceMappingURL=product.seed.js.map
//# debugId=9a744c55-5f81-575c-90ab-401163391a02
