"use strict";
!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="8a503f89-f65f-58b6-9155-b0850018e389")}catch(e){}}();

Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersSeed = void 0;
const bcrypt_1 = require("bcrypt");
exports.UsersSeed = [
    {
        id: 0,
        fullname: 'system',
        username: 'system',
        email: 'system@heystetik.com',
        password: (0, bcrypt_1.hashSync)('P@ssw0rd', 12),
        gender: 'Laki-laki',
        roleId: 1,
        is_active: true,
        finish_register: true,
    },
    {
        fullname: 'Superadmin',
        username: 'superadmin',
        email: 'superadmin@gmail.com',
        password: (0, bcrypt_1.hashSync)('P@ssw0rd', 12),
        no_phone: '+6284567890987',
        gender: 'Laki-laki',
        address: 'Jalan Pemuda',
        photo_profile: 'photo_profile',
        referral_code: 'referral_code',
        roleId: 1,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Doctor',
        username: 'doctor',
        email: 'doctor@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+62834567890992',
        gender: 'Laki-laki',
        address: 'Jalan Pemuda',
        photo_profile: 'photo_profile',
        referral_code: 'referral_code',
        roleId: 2,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Customer',
        username: 'customer',
        email: 'customer@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+628567890987',
        gender: 'Perempuan',
        address: 'Jalan Pemuda',
        photo_profile: 'photo_profile',
        referral_code: 'referral_code',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'John Doe',
        username: 'johndoe',
        email: 'johndoe@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281234567890',
        gender: 'Laki-laki',
        address: 'Jalan Sudirman No. 123',
        photo_profile: 'profile1.jpg',
        referral_code: 'ABC123',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Jane Smith',
        username: 'janesmith',
        email: 'janesmith@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6287654321098',
        gender: 'Perempuan',
        address: 'Jalan Gatot Subroto No. 456',
        photo_profile: 'profile2.jpg',
        referral_code: 'DEF456',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Michael Johnson',
        username: 'michaeljohnson',
        email: 'michaeljohnson@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281112223334',
        gender: 'Laki-laki',
        address: 'Jalan Thamrin No. 789',
        photo_profile: 'profile3.jpg',
        referral_code: 'GHI789',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Sarah Johnson',
        username: 'sarahjohnson',
        email: 'sarahjohnson@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281234567891',
        gender: 'Perempuan',
        address: 'Jalan Ahmad Yani No. 789',
        photo_profile: 'profile4.jpg',
        referral_code: 'JKL123',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'David Wilson',
        username: 'davidwilson',
        email: 'davidwilson@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6287654321099',
        gender: 'Laki-laki',
        address: 'Jalan Merdeka No. 456',
        photo_profile: 'profile5.jpg',
        referral_code: 'MNO456',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Emily Davis',
        username: 'emilydavis',
        email: 'emilydavis@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281112223335',
        gender: 'Perempuan',
        address: 'Jalan Sudirman No. 890',
        photo_profile: 'profile6.jpg',
        referral_code: 'PQR789',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Matthew Anderson',
        username: 'matthewanderson',
        email: 'matthewanderson@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281234567892',
        gender: 'Laki-laki',
        address: 'Jalan Thamrin No. 123',
        photo_profile: 'profile7.jpg',
        referral_code: 'STU123',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Olivia Martinez',
        username: 'oliviamartinez',
        email: 'oliviamartinez@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6287654321100',
        gender: 'Perempuan',
        address: 'Jalan Gatot Subroto No. 456',
        photo_profile: 'profile8.jpg',
        referral_code: 'VWX456',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Daniel Thompson',
        username: 'danielthompson',
        email: 'danielthompson@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281112223336',
        gender: 'Laki-laki',
        address: 'Jalan Sudirman No. 789',
        photo_profile: 'profile9.jpg',
        referral_code: 'YZA789',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Sophia Clark',
        username: 'sophiaclark',
        email: 'sophiaclark@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281234567893',
        gender: 'Perempuan',
        address: 'Jalan Sudirman No. 456',
        photo_profile: 'profile10.jpg',
        referral_code: 'BCD123',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'James Turner',
        username: 'jamesturner',
        email: 'jamesturner@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6287654321101',
        gender: 'Laki-laki',
        address: 'Jalan Gatot Subroto No. 789',
        photo_profile: 'profile11.jpg',
        referral_code: 'DEF456',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Ava Lewis',
        username: 'avalewis',
        email: 'avalewis@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281112223337',
        gender: 'Perempuan',
        address: 'Jalan Thamrin No. 123',
        photo_profile: 'profile12.jpg',
        referral_code: 'EFG789',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Liam Walker',
        username: 'liamwalker',
        email: 'liamwalker@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281234567894',
        gender: 'Laki-laki',
        address: 'Jalan Ahmad Yani No. 456',
        photo_profile: 'profile13.jpg',
        referral_code: 'FGH123',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Mia Hall',
        username: 'miahall',
        email: 'miahall@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6287654321102',
        gender: 'Perempuan',
        address: 'Jalan Merdeka No. 789',
        photo_profile: 'profile14.jpg',
        referral_code: 'GHI456',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Noah Adams',
        username: 'noahadams',
        email: 'noahadams@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6281112223338',
        gender: 'Laki-laki',
        address: 'Jalan Sudirman No. 890',
        photo_profile: 'profile15.jpg',
        referral_code: 'HIJ789',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
    {
        fullname: 'Ahrul Syamil',
        username: 'ahrulsyamil',
        email: 'ahrulsyamilulum@gmail.com',
        password: (0, bcrypt_1.hashSync)('123456', 12),
        no_phone: '+6283818924607',
        gender: 'Laki-laki',
        address: 'Kp. Muara Bawah RT 04 RW 04 Desa Kopo Kecamatan Cisarua, Bogor, Jawa Barat',
        photo_profile: 'profile15.jpg',
        referral_code: 'HIJ789',
        roleId: 3,
        is_active: true,
        verified_phone_at: new Date(),
        verified_email_at: new Date(),
        finish_register: true,
    },
];
//# sourceMappingURL=users.seed.js.map
//# debugId=8a503f89-f65f-58b6-9155-b0850018e389
